### ISSUE TITLE
Building with qemu?

### ISSUE THREAD

**Issue by dakami** [datto/RDPMux#12]
I'm trying to get a working RDP build of qemu up and running, and it's just not clear the sequence of library dependencies needed.  Any tips?

**Comment by SriRamanujam** [comment]
You will need librdpmux built and in the library search path and the headers in the header search path, and then you will need to build QEMU from https://github.com/datto/qemu/tree/f27-stable-2.10-rdpmux here with `--enable-mux` passed to the configure script.

**Comment by dakami** [comment]
I didn't think I'd missed something that simple.  Which version of msgpack do you build against, on what platform?  Ubuntu and git fail on msgpack.

> /home/u/d/RDPMux/src/RDPServerWorker.cpp:137:29:   required from here
> /usr/local/include/msgpack/v1/object.hpp:631:11: error: ‘const class std::vector<short unsigned int>’ has no member named ‘msgpack_pack’; did you mean ‘emplace_back’?
>          v.msgpack_pack(o);
>          ~~^~~~~~~~~~~~
>          emplace_back
> 
>

**Comment by SriRamanujam** [comment]
We build on Ubuntu 16.04 using the msgpack library shipped in the repositories, which appears to be 0.5.7: https://packages.ubuntu.com/xenial/libmsgpack-dev
